---

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "Remove unneeded dependencies"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Unzip backend files"
  become: true
  unarchive:
    src: artifacts.tar.gz
    dest: .

- name: "start backend with pm2"
  become: true
  shell: |
    pm2 delete all
    pm2 start npm -- start